// ============================================================
// imm_gen.v — Immediate Generator
// Generated by rtl_renderer.py from microarch.yaml
// Architecture : RISC-V RV32I
// XLEN         : 32
// Formats      : I-type, S-type, B-type, U-type, J-type
// IMM type wid : 3 bits
// DO NOT EDIT — regenerate from microarch.yaml
// ============================================================
module imm_gen (
    /* verilator lint_off UNUSED */
    input  logic [31:0]          instr,
    /* verilator lint_on UNUSED */
    input  logic [2:0] imm_type,
    output logic [31:0]  imm_out
);

// Immediate type encodings (from microarch.yaml):
// I-type-type = 3'b000
// S-type-type = 3'b001
// B-type-type = 3'b010
// U-type-type = 3'b011
// J-type-type = 3'b100

always_comb begin
    case (imm_type)
        default: imm_out = 32'b0;
    endcase
end

endmodule
