// ============================================================
// control.v — CPU Control Decoder
// Generated by rtl_renderer.py from microarch.yaml
// Architecture : RISC-V RV32I
// Instructions : 37
// ALU op width : 4 bits (10 operations)
// IMM type wid : 3 bits
// WB src width : 2 bits
// MEM sz width : 2 bits
// DO NOT EDIT — regenerate from microarch.yaml
// ============================================================
module control (
    input  logic [6:0]        opcode,
    input  logic [2:0]        funct3,
    input  logic              funct7b5,
    // ALU control
    output logic [3:0] alu_op,
    output logic              alu_src_b,    // 0=rs2, 1=imm
    output logic [1:0]        alu_src_a,    // 2'b00=rs1, 2'b01=pc, 2'b10=zero
    // Writeback
    output logic [1:0] result_src,
    output logic              reg_write,
    // Memory
    output logic              mem_read,
    output logic              mem_write,
    output logic [1:0] mem_size,
    output logic              mem_extend,   // 0=sign-extend, 1=zero-extend
    // Branch / Jump
    output logic              branch,
    output logic [2:0]        branch_type,  // = funct3 for RISC-V branches
    output logic              jump,
    output logic              jump_type,    // 0=JAL (PC-rel), 1=JALR (reg+imm)
    // Immediate format selector
    output logic [2:0] imm_type
);

always_comb begin
    // Safe defaults — prevents latches in synthesis
    alu_op      = 4'b0;
    alu_src_b   = 1'b0;
    alu_src_a   = 2'b00;
    result_src  = 2'b0;
    reg_write   = 1'b0;
    mem_read    = 1'b0;
    mem_write   = 1'b0;
    mem_size    = 2'b0;
    mem_extend  = 1'b0;
    branch      = 1'b0;
    branch_type = 3'b000;
    jump        = 1'b0;
    jump_type   = 1'b0;
    imm_type    = 3'b0;

    case (opcode)
        // ── ADD, SUB, SLL, SLT, SLTU, XOR, SRL, SRA, OR, AND ──────────────────────────────
        7'b0110011: begin
            case (funct3)
                // ADD / SUB — split by funct7b5
                3'b000: begin
                    if (funct7b5 == 1'b0) begin  // ADD
                        alu_op     = 4'b0000;
                        alu_src_b  = 1'b0;
                        result_src = 2'b00;
                        reg_write  = 1'b1;
                    end
                    if (funct7b5 == 1'b1) begin  // SUB
                        alu_op     = 4'b0001;
                        alu_src_b  = 1'b0;
                        result_src = 2'b00;
                        reg_write  = 1'b1;
                    end
                end
                // SLL
                3'b001: begin
                    alu_op      = 4'b0101;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                end
                // SLT
                3'b010: begin
                    alu_op      = 4'b1000;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                end
                // SLTU
                3'b011: begin
                    alu_op      = 4'b1001;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                end
                // XOR
                3'b100: begin
                    alu_op      = 4'b0100;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                end
                // SRL / SRA — split by funct7b5
                3'b101: begin
                    if (funct7b5 == 1'b0) begin  // SRL
                        alu_op     = 4'b0110;
                        alu_src_b  = 1'b0;
                        result_src = 2'b00;
                        reg_write  = 1'b1;
                    end
                    if (funct7b5 == 1'b1) begin  // SRA
                        alu_op     = 4'b0111;
                        alu_src_b  = 1'b0;
                        result_src = 2'b00;
                        reg_write  = 1'b1;
                    end
                end
                // OR
                3'b110: begin
                    alu_op      = 4'b0011;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                end
                // AND
                3'b111: begin
                    alu_op      = 4'b0010;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                end
                default: begin end
            endcase
        end

        // ── ADDI, SLTI, SLTIU, XORI, ORI, ANDI, SLLI, SRLI, SRAI ──────────────────────────────
        7'b0010011: begin
            case (funct3)
                // ADDI
                3'b000: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                // SLTI
                3'b010: begin
                    alu_op      = 4'b1000;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                // SLTIU
                3'b011: begin
                    alu_op      = 4'b1001;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                // XORI
                3'b100: begin
                    alu_op      = 4'b0100;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                // ORI
                3'b110: begin
                    alu_op      = 4'b0011;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                // ANDI
                3'b111: begin
                    alu_op      = 4'b0010;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                // SLLI
                3'b001: begin
                    alu_op      = 4'b0101;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b1;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                // SRLI / SRAI — split by funct7b5
                3'b101: begin
                    if (funct7b5 == 1'b0) begin  // SRLI
                        alu_op     = 4'b0110;
                        alu_src_b  = 1'b1;
                        result_src = 2'b00;
                        reg_write  = 1'b1;
                        imm_type   = 3'b000;
                    end
                    if (funct7b5 == 1'b1) begin  // SRAI
                        alu_op     = 4'b0111;
                        alu_src_b  = 1'b1;
                        result_src = 2'b00;
                        reg_write  = 1'b1;
                        imm_type   = 3'b000;
                    end
                end
                default: begin end
            endcase
        end

        // ── LUI ──────────────────────────────
        7'b0110111: begin
            alu_op      = 4'b0000;
            alu_src_b   = 1'b1;
            alu_src_a   = 2'b10;
            result_src  = 2'b11;
            reg_write   = 1'b1;
            mem_read    = 1'b0;
            mem_write   = 1'b0;
            branch      = 1'b0;
            jump        = 1'b0;
            imm_type    = 3'b011;
        end

        // ── AUIPC ──────────────────────────────
        7'b0010111: begin
            alu_op      = 4'b0000;
            alu_src_b   = 1'b1;
            alu_src_a   = 2'b01;
            result_src  = 2'b00;
            reg_write   = 1'b1;
            mem_read    = 1'b0;
            mem_write   = 1'b0;
            branch      = 1'b0;
            jump        = 1'b0;
            imm_type    = 3'b011;
        end

        // ── JAL ──────────────────────────────
        7'b1101111: begin
            alu_op      = 4'b0000;
            alu_src_b   = 1'b1;
            alu_src_a   = 2'b01;
            result_src  = 2'b10;
            reg_write   = 1'b1;
            mem_read    = 1'b0;
            mem_write   = 1'b0;
            branch      = 1'b0;
            jump        = 1'b1;
            jump_type   = 1'b0;
            imm_type    = 3'b100;
        end

        // ── JALR ──────────────────────────────
        7'b1100111: begin
            alu_op      = 4'b0000;
            alu_src_b   = 1'b1;
            alu_src_a   = 2'b00;
            result_src  = 2'b10;
            reg_write   = 1'b1;
            mem_read    = 1'b0;
            mem_write   = 1'b0;
            branch      = 1'b0;
            jump        = 1'b1;
            jump_type   = 1'b1;
            imm_type    = 3'b000;
        end

        // ── BEQ, BNE, BLT, BGE, BLTU, BGEU ──────────────────────────────
        7'b1100011: begin
            case (funct3)
                // BEQ
                3'b000: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b0;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b1;
                    branch_type = 3'b000;
                    jump        = 1'b0;
                    imm_type    = 3'b010;
                end
                // BNE
                3'b001: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b0;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b1;
                    branch_type = 3'b001;
                    jump        = 1'b0;
                    imm_type    = 3'b010;
                end
                // BLT
                3'b100: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b0;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b1;
                    branch_type = 3'b100;
                    jump        = 1'b0;
                    imm_type    = 3'b010;
                end
                // BGE
                3'b101: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b0;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b1;
                    branch_type = 3'b101;
                    jump        = 1'b0;
                    imm_type    = 3'b010;
                end
                // BLTU
                3'b110: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b0;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b1;
                    branch_type = 3'b110;
                    jump        = 1'b0;
                    imm_type    = 3'b010;
                end
                // BGEU
                3'b111: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b0;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b0;
                    mem_read    = 1'b0;
                    mem_write   = 1'b0;
                    branch      = 1'b1;
                    branch_type = 3'b111;
                    jump        = 1'b0;
                    imm_type    = 3'b010;
                end
                default: begin end
            endcase
        end

        // ── LB, LH, LW, LBU, LHU ──────────────────────────────
        7'b0000011: begin
            case (funct3)
                // LB
                3'b000: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b01;
                    reg_write   = 1'b1;
                    mem_read    = 1'b1;
                    mem_write   = 1'b0;
                    mem_size    = 2'b00;
                    mem_extend  = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                // LH
                3'b001: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b01;
                    reg_write   = 1'b1;
                    mem_read    = 1'b1;
                    mem_write   = 1'b0;
                    mem_size    = 2'b01;
                    mem_extend  = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                // LW
                3'b010: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b01;
                    reg_write   = 1'b1;
                    mem_read    = 1'b1;
                    mem_write   = 1'b0;
                    mem_size    = 2'b10;
                    mem_extend  = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                // LBU
                3'b100: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b01;
                    reg_write   = 1'b1;
                    mem_read    = 1'b1;
                    mem_write   = 1'b0;
                    mem_size    = 2'b00;
                    mem_extend  = 1'b1;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                // LHU
                3'b101: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b01;
                    reg_write   = 1'b1;
                    mem_read    = 1'b1;
                    mem_write   = 1'b0;
                    mem_size    = 2'b01;
                    mem_extend  = 1'b1;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b000;
                end
                default: begin end
            endcase
        end

        // ── SB, SH, SW ──────────────────────────────
        7'b0100011: begin
            case (funct3)
                // SB
                3'b000: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b0;
                    mem_read    = 1'b0;
                    mem_write   = 1'b1;
                    mem_size    = 2'b00;
                    mem_extend  = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b001;
                end
                // SH
                3'b001: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b0;
                    mem_read    = 1'b0;
                    mem_write   = 1'b1;
                    mem_size    = 2'b01;
                    mem_extend  = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b001;
                end
                // SW
                3'b010: begin
                    alu_op      = 4'b0000;
                    alu_src_b   = 1'b1;
                    alu_src_a   = 2'b00;
                    result_src  = 2'b00;
                    reg_write   = 1'b0;
                    mem_read    = 1'b0;
                    mem_write   = 1'b1;
                    mem_size    = 2'b10;
                    mem_extend  = 1'b0;
                    branch      = 1'b0;
                    jump        = 1'b0;
                    imm_type    = 3'b001;
                end
                default: begin end
            endcase
        end

        default: begin end
    endcase
end

endmodule
