// ============================================================
// imm_gen.v — Immediate Generator
// Generated by rtl_renderer.py from microarch.yaml
// Architecture : RISC-V RV32I
// XLEN         : 32
// Formats      : I, S, B, U, J
// IMM type wid : 3 bits
// DO NOT EDIT — regenerate from microarch.yaml
// ============================================================
module imm_gen (
    /* verilator lint_off UNUSED */
    input  logic [31:0]          instr,
    /* verilator lint_on UNUSED */
    input  logic [2:0] imm_type,
    output logic [31:0]  imm
);

// Immediate type encodings (from microarch.yaml):
// I-type = 3'b000
// S-type = 3'b001
// B-type = 3'b010
// U-type = 3'b011
// J-type = 3'b100

always_comb begin
    case (imm_type)
        // ── I-type ─────────────────────────────────────────────
        // sign_ext({ instr[31:20] })  →  20-bit sign replication
        3'b000: imm = {{20{instr[31]}}, instr[31:20]};

        // ── S-type ─────────────────────────────────────────────
        // sign_ext({ instr[31:25], instr[11:7] })
        3'b001: imm = {{20{instr[31]}}, instr[31:25], instr[11:7]};

        // ── B-type ─────────────────────────────────────────────
        // sign_ext({ instr[31], instr[7], instr[30:25], instr[11:8], 1'b0 })
        3'b010: imm = {{19{instr[31]}}, instr[31], instr[7], instr[30:25], instr[11:8], 1'b0};

        // ── U-type ─────────────────────────────────────────────
        // { instr[31:12], 12'b0 }
        3'b011: imm = {instr[31:12], 12'b0};

        // ── J-type ─────────────────────────────────────────────
        // sign_ext({ instr[31], instr[19:12], instr[20], instr[30:21], 1'b0 })
        3'b100: imm = {{11{instr[31]}}, instr[31], instr[19:12], instr[20], instr[30:21], 1'b0};

        default: imm = 32'b0;
    endcase
end

endmodule
