// ============================================================
// tb_cpu.v — Simulation Testbench
// Generated by rtl_renderer.py from microarch.yaml
// Architecture : RISC-V RV32I
// Mem depth    : 1024 words  (4096 bytes)
// Hex file     : program.hex
// tohost addr  : 0x80001000
// DO NOT EDIT — regenerate via generate_cpu.py
// ============================================================
`timescale 1ns/1ps

module tb_cpu;

// ── Clock & Reset ─────────────────────────────────────────────────────────────
logic clk    = 0;
logic resetn = 0;

always #5 clk = ~clk;               // 100 MHz

initial begin
    #2  resetn = 0;
    #20 resetn = 1;                  // deassert reset after 20 ns
end

// ── CPU bus signals ───────────────────────────────────────────────────────────
logic [31:0] imem_addr;
logic [31:0] imem_rdata;
logic [31:0] dmem_addr;
logic [31:0] dmem_wdata;
logic [3:0]  dmem_wstrb;
logic        dmem_read;
logic        dmem_write;
logic [31:0] dmem_rdata;

// ── DUT instantiation ─────────────────────────────────────────────────────────
cpu u_cpu (
    .clk         (clk),
    .resetn      (resetn),
    .imem_rdata  (imem_rdata),
    .dmem_rdata  (dmem_rdata),
    .imem_addr   (imem_addr),
    .dmem_addr   (dmem_addr),
    .dmem_wdata  (dmem_wdata),
    .dmem_wstrb  (dmem_wstrb),
    .dmem_read   (dmem_read),
    .dmem_write  (dmem_write)
);

// ── Instruction Memory (ROM — only in testbench) ──────────────────────────────
// Word-addressed by imem_addr[31:2]; imem_addr[1:0] always 0 for valid instr.
logic [31:0] imem [0 : 1023];

initial $readmemh("program.hex", imem);

assign imem_rdata = imem[imem_addr[31:2]];

// ── Data Memory (SRAM — only in testbench) ────────────────────────────────────
// Byte-addressable; internally word-organized. Byte enables from dmem_wstrb.
logic [7:0] dmem_bytes [0 : 4095];

// Synchronous byte-lane write
always_ff @(posedge clk) begin
    if (dmem_write) begin
        if (dmem_wstrb[0]) dmem_bytes[dmem_addr + 0] <= dmem_wdata[7:0];
        if (dmem_wstrb[1]) dmem_bytes[dmem_addr + 1] <= dmem_wdata[15:8];
        if (dmem_wstrb[2]) dmem_bytes[dmem_addr + 2] <= dmem_wdata[23:16];
        if (dmem_wstrb[3]) dmem_bytes[dmem_addr + 3] <= dmem_wdata[31:24];
    end
end

// Asynchronous word read (load_store.v already handles byte selection / extension)
assign dmem_rdata = {
    dmem_bytes[dmem_addr + 3],
    dmem_bytes[dmem_addr + 2],
    dmem_bytes[dmem_addr + 1],
    dmem_bytes[dmem_addr]
};

// ── tohost / HTIF — pass/fail detection for riscv-tests ──────────────────────
// Per riscv-tests convention:
//   PASS: tohost  = 1          (test number 1 shifted left, +1)
//   FAIL: tohost != 0 && != 1  (test number of the failing test, ≥ 3)
localparam logic [31:0] TOHOST_ADDR = 32'h80001000;
logic [31:0] tohost_val;

always_ff @(posedge clk) begin
    if (dmem_write && dmem_addr == TOHOST_ADDR) begin
        tohost_val <= dmem_wdata;
    end
end

always_ff @(posedge clk) begin
    if (tohost_val != 0) begin
        if (tohost_val == 32'd1) begin
            $display("[TB] PASS — tohost=0x%08h at time %0t", tohost_val, $time);
            $finish;
        end else begin
            $display("[TB] FAIL — tohost=0x%08h (failing test #%0d) at time %0t",
                     tohost_val, tohost_val >> 1, $time);
            $finish;
        end
    end
end

// ── Timeout watchdog ──────────────────────────────────────────────────────────
initial begin
    #2_000_000;   // 2 ms simulation limit
    $display("[TB] TIMEOUT — simulation exceeded 2ms without tohost write");
    $finish;
end

// ── Optional VCD dump ─────────────────────────────────────────────────────────
initial begin
    if ($test$plusargs("DUMP")) begin
        $dumpfile("cpu.vcd");
        $dumpvars(0, tb_cpu);
    end
end

endmodule
